"""稳定 API 响应码。"""

from __future__ import annotations

from enum import IntEnum, StrEnum


class ErrorCode(IntEnum):
    """跨端稳定整数错误码。"""

    INTERNAL_ERROR = -1
    VALIDATION_ERROR = 10001
    UNAUTHORIZED = 10002
    FORBIDDEN = 10003
    NOT_FOUND = 10004
    CONFLICT = 10005
    RATE_LIMITED = 10006
    SERVICE_UNAVAILABLE = 10007
    REGISTRATION_DISABLED = 11001
    ACCOUNT_IDENTIFIER_UNAVAILABLE = 11002
    REGISTRATION_RATE_LIMITED = 11003


class ErrorMessage(StrEnum):
    """与错误码配套的稳定消息标识。"""

    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    REGISTRATION_DISABLED = "REGISTRATION_DISABLED"
    ACCOUNT_IDENTIFIER_UNAVAILABLE = "ACCOUNT_IDENTIFIER_UNAVAILABLE"
    REGISTRATION_RATE_LIMITED = "REGISTRATION_RATE_LIMITED"
