"""持久化批量任务、导入回执、候选用途与收藏。"""

import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString

from alembic import op

revision = "20260906_0014"
down_revision = "20260906_0013"
branch_labels = None
depends_on = None


TABLE_COMMENTS = {
    "ai_batch_items": "批量任务逐章进度与生成时来源版本",
    "ai_batches": "作者主动发起的逐章批量摘要或一致性检查",
    "import_receipts": "导入原子提交的幂等回执",
}

COLUMN_COMMENTS = {
    "ai_batch_items": {
        "batch_id": "所属批次标识",
        "created_at": "创建时间（UTC）",
        "document_id": "来源章节标识快照",
        "document_version": "提交批次时的正文版本",
        "error_code": "脱敏失败原因码",
        "id": "批次章节项唯一标识",
        "position": "作者选择的执行顺序",
        "result_id": "生成的摘要或分析结果标识",
        "source_order": "来源章节之前的叙述顺序摘要",
        "status": "queued、running、succeeded、failed、cancelled 或 stale",
        "task_id": "最近一次关联 AI 任务标识快照",
        "updated_at": "最后更新时间（UTC）",
    },
    "ai_batches": {
        "created_at": "创建时间（UTC）",
        "id": "批次唯一标识",
        "instruction": "作者为本批次提交的任务要求",
        "model_id": "作者选择的模型标识快照",
        "owner_id": "发起作者标识",
        "project_id": "所属作品标识",
        "provider_config_id": "作者选择的 Provider 配置标识快照",
        "request_hash": "任务参数摘要，防止幂等键被复用为其他请求",
        "request_id": "客户端幂等请求标识",
        "status": "批次调度状态，重启后暂停",
        "task_type": "summary 或 consistency",
        "updated_at": "最后更新时间（UTC）",
        "use_recall": "作者明确选择所选范围内的前两章原文作为参考",
    },
    "ai_results": {"pinned": "作者收藏后不自动清理此结果所属任务", "purpose": "候选用途：正文、摘要或分析"},
    "import_receipts": {
        "created_at": "创建时间（UTC）",
        "id": "客户端导入请求标识",
        "imported": "实际新增章节数量",
        "owner_id": "发起导入的作者",
        "payload_hash": "导入参数摘要，识别同请求不同内容",
        "project_id": "导入目标作品",
        "skipped": "作者选择跳过的同名章节数量",
        "updated_at": "最后更新时间（UTC）",
    },
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_batches",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间（UTC）",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="最后更新时间（UTC）",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="批次唯一标识"),
        sa.Column("owner_id", sa.Uuid(), nullable=False, comment="发起作者标识"),
        sa.Column("project_id", sa.Uuid(), nullable=False, comment="所属作品标识"),
        sa.Column("request_id", sa.Uuid(), nullable=False, comment="客户端幂等请求标识"),
        sa.Column(
            "request_hash",
            AutoString(),
            nullable=False,
            comment="任务参数摘要，防止幂等键被复用为其他请求",
        ),
        sa.Column("provider_config_id", sa.Uuid(), nullable=False, comment="作者选择的 Provider 配置标识快照"),
        sa.Column("model_id", sa.Uuid(), nullable=True, comment="作者选择的模型标识快照"),
        sa.Column("task_type", AutoString(), nullable=False, comment="summary 或 consistency"),
        sa.Column("instruction", sa.Text(), nullable=False, comment="作者为本批次提交的任务要求"),
        sa.Column("use_recall", sa.Boolean(), nullable=False, comment="作者明确选择所选范围内的前两章原文作为参考"),
        sa.Column("status", AutoString(), nullable=False, comment="批次调度状态，重启后暂停"),
        sa.CheckConstraint(
            "status IN ('queued','running','paused','completed','cancelled')", name="ck_ai_batches_status"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "request_id", name="uq_ai_batches_owner_request"),
        comment="作者主动发起的逐章批量摘要或一致性检查",
    )
    op.create_index("ix_ai_batches_owner_status", "ai_batches", ["owner_id", "status"], unique=False)
    op.create_table(
        "import_receipts",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间（UTC）",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="最后更新时间（UTC）",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="客户端导入请求标识"),
        sa.Column("owner_id", sa.Uuid(), nullable=False, comment="发起导入的作者"),
        sa.Column("project_id", sa.Uuid(), nullable=False, comment="导入目标作品"),
        sa.Column(
            "payload_hash",
            AutoString(),
            nullable=False,
            comment="导入参数摘要，识别同请求不同内容",
        ),
        sa.Column("imported", sa.Integer(), nullable=False, comment="实际新增章节数量"),
        sa.Column("skipped", sa.Integer(), nullable=False, comment="作者选择跳过的同名章节数量"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="导入原子提交的幂等回执",
    )
    op.create_table(
        "ai_batch_items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间（UTC）",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="最后更新时间（UTC）",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="批次章节项唯一标识"),
        sa.Column("batch_id", sa.Uuid(), nullable=False, comment="所属批次标识"),
        sa.Column("document_id", sa.Uuid(), nullable=False, comment="来源章节标识快照"),
        sa.Column("document_version", sa.Integer(), nullable=False, comment="提交批次时的正文版本"),
        sa.Column("source_order", AutoString(), nullable=False, comment="来源章节之前的叙述顺序摘要"),
        sa.Column("position", sa.Integer(), nullable=False, comment="作者选择的执行顺序"),
        sa.Column(
            "status",
            AutoString(),
            nullable=False,
            comment="queued、running、succeeded、failed、cancelled 或 stale",
        ),
        sa.Column("task_id", sa.Uuid(), nullable=True, comment="最近一次关联 AI 任务标识快照"),
        sa.Column("error_code", AutoString(), nullable=True, comment="脱敏失败原因码"),
        sa.Column("result_id", sa.Uuid(), nullable=True, comment="生成的摘要或分析结果标识"),
        sa.ForeignKeyConstraint(["batch_id"], ["ai_batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "document_id", name="uq_ai_batch_items_document"),
        comment="批量任务逐章进度与生成时来源版本",
    )
    op.create_index("ix_ai_batch_items_batch_position", "ai_batch_items", ["batch_id", "position"], unique=False)
    # ### end Alembic commands ###
    with op.batch_alter_table("ai_results") as batch:
        batch.add_column(
            sa.Column(
                "purpose",
                sa.String(),
                nullable=False,
                server_default=sa.text("'manuscript'"),
                comment="候选用途：正文、摘要或分析",
            )
        )
        batch.add_column(
            sa.Column(
                "pinned",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
                comment="作者收藏后不自动清理此结果所属任务",
            )
        )
        batch.drop_constraint("ck_ai_results_status", type_="check")
        batch.drop_constraint("ck_ai_results_state_fields", type_="check")
        batch.create_check_constraint("ck_ai_results_status", "status IN ('candidate','applied','accepted','rejected')")
        batch.create_check_constraint(
            "ck_ai_results_state_fields",
            "(status = 'candidate' AND applied_document_id IS NULL AND decided_at IS NULL) OR "
            "(status = 'applied' AND applied_document_id IS NOT NULL AND decided_at IS NOT NULL) OR "
            "(status IN ('accepted','rejected') AND applied_document_id IS NULL AND decided_at IS "
            "NOT NULL)",
        )
    op.execute(
        "UPDATE ai_results SET purpose='analysis' WHERE task_id IN "
        "(SELECT id FROM ai_tasks WHERE task_type IN ('consistency','extract_settings'))"
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.create_index(
            "ix_document_contents_search",
            "document_contents",
            ["content"],
            postgresql_using="gin",
            postgresql_ops={"content": "gin_trgm_ops"},
        )


def downgrade() -> None:

    if op.get_bind().dialect.name == "postgresql":
        op.drop_index("ix_document_contents_search", table_name="document_contents")
    op.execute("UPDATE ai_results SET status='rejected' WHERE status='accepted'")
    with op.batch_alter_table("ai_results") as batch:
        batch.drop_constraint("ck_ai_results_status", type_="check")
        batch.drop_constraint("ck_ai_results_state_fields", type_="check")
        batch.create_check_constraint("ck_ai_results_status", "status IN ('candidate','applied','rejected')")
        batch.create_check_constraint(
            "ck_ai_results_state_fields",
            "(status = 'candidate' AND applied_document_id IS NULL AND decided_at IS NULL) OR "
            "(status = 'applied' AND applied_document_id IS NOT NULL AND decided_at IS NOT NULL) OR "
            "(status = 'rejected' AND applied_document_id IS NULL AND decided_at IS NOT NULL)",
        )
        batch.drop_column("pinned")
        batch.drop_column("purpose")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_batch_items_batch_position", table_name="ai_batch_items")
    op.drop_table("ai_batch_items")
    op.drop_table("import_receipts")
    op.drop_index("ix_ai_batches_owner_status", table_name="ai_batches")
    op.drop_table("ai_batches")
    # ### end Alembic commands ###
